baseURL = "http://angelhpascual.github.io"
languageCode = "en-us"
title = "angelhpascual @ Blog "
theme = "hugo-theme-nix"

[menu]
  [[menu.header]]
    name = "post"
    weight = 1
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

[params]


  GithubID = "angelhpascual"

  BitbucketID = "angelhpascual"
  TwitterID = "angelhernandev"

  LinkedInID = "angelhpascual"
  GoogleplusID = "angelhpascual"
  FacebookID = "angelhpascual"
  InstagramID = "angelsardino"
  TelegramID = "angelhpascual"
  Name = "angelhpascual"
  HeaderUsername = "angelhpascual"
  HeaderHostname = "hostname"
  Email = "angelhpascual@gmail.com"

  Mobile = "+34 648-72-56-22"
  About = "👋 Hi visitor! I'm Ángel and this is my web site made by Hugo framework. I like developing web sites using differents technologies like Hugo, Reactjs, Python. On this website you can expect my projects and blog my posts about everything that I love."
  ProfilePicture = "/10014290_10203504466196792_66633545_o.jpg"
  GoogleAnalytics = "your_google_analytics_id"
